server:
  port: 80

spring:
  application:
    name: cloud-consumer-order80
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/taotao?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect